from flask import Flask, render_template, request
import Saa  # Import your Saa.py script
import tkinter as tk
import io
import sys

app = Flask(__name__)

# Redirect stdout to a StringIO object to capture Tkinter output
sys.stdout = io.StringIO()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/run_saa', methods=['GET', 'POST'])
def run_saa():
    if request.method == 'POST':
        # Restore stdout
        sys.stdout = sys.__stdout__
        
        # Run Saa.py and capture its output
        root = tk.Tk()
        output = tk.Text(root)
        output.pack()
        
        # Run the Saa.py script
        Saa.main()
        
        # Get the output generated by Tkinter
        output_text = sys.stdout.getvalue()
        sys.stdout = io.StringIO()  # Reset stdout
        
        return output_text
    else:
        return "Use POST method to run Saa.py."

if __name__ == '__main__':
    app.run(debug=True)
